/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.k33ptoo.components.KButton;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author adrian
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {
        initComponents();
    }

    

    public JLabel getjNomUsuari() {
        return jNomUsuari;
    }

    public void setjNomUsuari(JLabel jNomUsuari) {
        this.jNomUsuari = jNomUsuari;
    }

    public JTextField getNomUsuari() {
        return nomUsuari;
    }

    public void setNomUsuari(JTextField nomUsuari) {
        this.nomUsuari = nomUsuari;
    }

    public ButtonGroup getButtonGroup1() {
        return buttonGroup1;
    }

    public void setButtonGroup1(ButtonGroup buttonGroup1) {
        this.buttonGroup1 = buttonGroup1;
    }

    public KButton getKbtmJugar() {
        return KbtmJugar;
    }

    public void setKbtmJugar(KButton KbtmJugar) {
        this.KbtmJugar = KbtmJugar;
    }

    public KButton getkCarregar() {
        return kCarregar;
    }

    public void setkCarregar(KButton kCarregar) {
        this.kCarregar = kCarregar;
    }

    public KButton getKbtmRanking() {
        return kbtmRanking;
    }

    public void setKbtmRanking(KButton kbtmRanking) {
        this.kbtmRanking = kbtmRanking;
    }
    
    
    
    
    
    
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jNomUsuari = new javax.swing.JLabel();
        nomUsuari = new javax.swing.JTextField();
        KbtmJugar = new com.k33ptoo.components.KButton();
        kCarregar = new com.k33ptoo.components.KButton();
        kbtmRanking = new com.k33ptoo.components.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));

        kGradientPanel1.setBackground(new java.awt.Color(253, 251, 251));
        kGradientPanel1.setForeground(new java.awt.Color(254, 242, 242));
        kGradientPanel1.setkBorderRadius(5);
        kGradientPanel1.setkEndColor(new java.awt.Color(79, 62, 62));
        kGradientPanel1.setkStartColor(new java.awt.Color(191, 64, 61));
        kGradientPanel1.setkTransparentControls(false);
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Rachana", 0, 72)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Buscaminas");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 50, 330, 90));

        jNomUsuari.setBackground(new java.awt.Color(254, 254, 254));
        jNomUsuari.setFont(new java.awt.Font("Rachana", 0, 24)); // NOI18N
        jNomUsuari.setForeground(new java.awt.Color(254, 254, 254));
        jNomUsuari.setText("INTRODUEIX EL TEU NOM");
        jNomUsuari.setMaximumSize(new java.awt.Dimension(150, 20));
        jNomUsuari.setMinimumSize(new java.awt.Dimension(150, 20));
        kGradientPanel1.add(jNomUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 240, 50));

        nomUsuari.setBackground(new java.awt.Color(254, 254, 254));
        nomUsuari.setFont(new java.awt.Font("Rachana", 0, 24)); // NOI18N
        nomUsuari.setForeground(new java.awt.Color(254, 254, 254));
        nomUsuari.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, java.awt.Color.white));
        nomUsuari.setCaretColor(new java.awt.Color(254, 254, 254));
        nomUsuari.setMaximumSize(new java.awt.Dimension(150, 20));
        nomUsuari.setMinimumSize(new java.awt.Dimension(150, 20));
        nomUsuari.setOpaque(false);
        nomUsuari.setPreferredSize(new java.awt.Dimension(150, 20));
        nomUsuari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomUsuariActionPerformed(evt);
            }
        });
        kGradientPanel1.add(nomUsuari, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 180, 300, 50));

        KbtmJugar.setBackground(new java.awt.Color(1, 1, 1));
        KbtmJugar.setForeground(new java.awt.Color(1, 1, 1));
        KbtmJugar.setText("Jugar!");
        KbtmJugar.setFont(new java.awt.Font("Rachana", 1, 15)); // NOI18N
        KbtmJugar.setkBorderRadius(30);
        KbtmJugar.setkEndColor(new java.awt.Color(191, 64, 61));
        KbtmJugar.setkIndicatorThickness(5);
        KbtmJugar.setkStartColor(new java.awt.Color(79, 62, 62));
        KbtmJugar.setMaximumSize(new java.awt.Dimension(72, 31));
        KbtmJugar.setMinimumSize(new java.awt.Dimension(72, 31));
        kGradientPanel1.add(KbtmJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        kCarregar.setBackground(new java.awt.Color(1, 1, 1));
        kCarregar.setForeground(new java.awt.Color(1, 1, 1));
        kCarregar.setText("Carregar");
        kCarregar.setFont(new java.awt.Font("Rachana", 1, 15)); // NOI18N
        kCarregar.setkBorderRadius(30);
        kCarregar.setkEndColor(new java.awt.Color(191, 64, 61));
        kCarregar.setkIndicatorThickness(5);
        kCarregar.setkStartColor(new java.awt.Color(79, 62, 62));
        kCarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kCarregarActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kCarregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 350, -1, -1));

        kbtmRanking.setBackground(new java.awt.Color(1, 1, 1));
        kbtmRanking.setForeground(new java.awt.Color(1, 1, 1));
        kbtmRanking.setText("Ranking");
        kbtmRanking.setToolTipText("");
        kbtmRanking.setFont(new java.awt.Font("Rachana", 1, 15)); // NOI18N
        kbtmRanking.setkBorderRadius(30);
        kbtmRanking.setkEndColor(new java.awt.Color(191, 64, 61));
        kbtmRanking.setkIndicatorThickness(5);
        kbtmRanking.setkStartColor(new java.awt.Color(79, 62, 62));
        kbtmRanking.setMaximumSize(new java.awt.Dimension(72, 31));
        kbtmRanking.setMinimumSize(new java.awt.Dimension(72, 31));
        kbtmRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kbtmRankingActionPerformed(evt);
            }
        });
        kGradientPanel1.add(kbtmRanking, new org.netbeans.lib.awtextra.AbsoluteConstraints(677, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomUsuariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomUsuariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomUsuariActionPerformed

    private void kbtmRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kbtmRankingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kbtmRankingActionPerformed

    private void kCarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kCarregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kCarregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.k33ptoo.components.KButton KbtmJugar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNomUsuari;
    private com.k33ptoo.components.KButton kCarregar;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton kbtmRanking;
    private javax.swing.JTextField nomUsuari;
    // End of variables declaration//GEN-END:variables
}
