/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import com.k33ptoo.components.KButton;

/**
 *
 * @author adrian
 */
public class ViewDifficulty extends javax.swing.JDialog {

    /**
     * Creates new form ViewDificultat
     */
    public ViewDifficulty(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public KButton getRbDificil() {
        return rbDificil;
    }

    public void setRbDificil(KButton rbDificil) {
        this.rbDificil = rbDificil;
    }

    public KButton getRbFacil() {
        return rbFacil;
    }

    public void setRbFacil(KButton rbFacil) {
        this.rbFacil = rbFacil;
    }

    public KButton getRbNormal() {
        return rbNormal;
    }

    public void setRbNormal(KButton rbNormal) {
        this.rbNormal = rbNormal;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new com.k33ptoo.components.KGradientPanel();
        rbFacil = new com.k33ptoo.components.KButton();
        rbNormal = new com.k33ptoo.components.KButton();
        rbDificil = new com.k33ptoo.components.KButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 200));

        kGradientPanel1.setkEndColor(new java.awt.Color(79, 62, 62));
        kGradientPanel1.setkStartColor(new java.awt.Color(191, 64, 61));
        kGradientPanel1.setMinimumSize(new java.awt.Dimension(650, 200));
        kGradientPanel1.setOpaque(false);
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(650, 200));

        rbFacil.setBackground(new java.awt.Color(1, 1, 1));
        rbFacil.setForeground(new java.awt.Color(1, 1, 1));
        rbFacil.setText("Facil");
        rbFacil.setFont(new java.awt.Font("Rachana", 1, 15)); // NOI18N
        rbFacil.setkBorderRadius(30);
        rbFacil.setkEndColor(new java.awt.Color(191, 64, 61));
        rbFacil.setkIndicatorThickness(5);
        rbFacil.setkStartColor(new java.awt.Color(79, 62, 62));
        rbFacil.setMaximumSize(new java.awt.Dimension(185, 45));
        rbFacil.setMinimumSize(new java.awt.Dimension(185, 45));
        rbFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFacilActionPerformed(evt);
            }
        });

        rbNormal.setBackground(new java.awt.Color(1, 1, 1));
        rbNormal.setForeground(new java.awt.Color(1, 1, 1));
        rbNormal.setText("Mitg");
        rbNormal.setFont(new java.awt.Font("Rachana", 1, 15)); // NOI18N
        rbNormal.setkBorderRadius(30);
        rbNormal.setkEndColor(new java.awt.Color(191, 64, 61));
        rbNormal.setkIndicatorThickness(5);
        rbNormal.setkStartColor(new java.awt.Color(79, 62, 62));
        rbNormal.setMaximumSize(new java.awt.Dimension(185, 45));
        rbNormal.setMinimumSize(new java.awt.Dimension(185, 45));
        rbNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbNormalActionPerformed(evt);
            }
        });

        rbDificil.setBackground(new java.awt.Color(1, 1, 1));
        rbDificil.setForeground(new java.awt.Color(1, 1, 1));
        rbDificil.setText("Dificil");
        rbDificil.setFont(new java.awt.Font("Rachana", 1, 15)); // NOI18N
        rbDificil.setkBorderRadius(30);
        rbDificil.setkEndColor(new java.awt.Color(191, 64, 61));
        rbDificil.setkIndicatorThickness(5);
        rbDificil.setkStartColor(new java.awt.Color(79, 62, 62));
        rbDificil.setMaximumSize(new java.awt.Dimension(185, 45));
        rbDificil.setMinimumSize(new java.awt.Dimension(185, 45));
        rbDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDificilActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Rachana", 1, 64)); // NOI18N
        jLabel1.setText("Dificultat");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(rbNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(rbDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(211, 211, 211))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFacilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbFacilActionPerformed

    private void rbNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbNormalActionPerformed

    private void rbDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDificilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbDificilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewDifficulty.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ViewDifficulty dialog = new ViewDifficulty(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private com.k33ptoo.components.KGradientPanel kGradientPanel1;
    private com.k33ptoo.components.KButton rbDificil;
    private com.k33ptoo.components.KButton rbFacil;
    private com.k33ptoo.components.KButton rbNormal;
    // End of variables declaration//GEN-END:variables
}
